services:
  storage:
    image: redis
    volumes:
      - ./data:/data

  counter:
    image: blckbrrynvdr/netology-counter:v1.0.0
    working_dir: /app/counter
    ports:
      - 3001:3001
    volumes:
      - ./counter:/app/counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage

  library:
    image: blckbrrynvdr/netology-library:v1.0.0
    working_dir: /app/library
    ports:
      - 3002:3002
    volumes:
      - ./:/app
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage